#Test file migration and transformation for WHA using member info data.
rm -rf /grid/0/nfs/user/sfox/WHA_A_memberinfo.txt && rm -rf /grid/0/nfs/user/sfox/WHA_A_planinfo.txt
rm -rf /grid/0/nfs/user/sfox/WHA_A_pharmacyclaims.txt && rm -rf /grid/0/nfs/user/sfox/WHA_A_pharmacyclaims_amt.txt
pig -x tez /grid/0/nfs/user/sfox/Scripts/memberinfo_3.pig
pig -x tez /grid/0/nfs/user/sfox/Scripts/pharmacyclaims_2.pig
hive -f  /grid/0/nfs/user/sfox/Scripts/memberinfo_3.hql
hive -f /grid/0/nfs/user/sfox/Scripts/rxclaims.hql
#B_001_InsuredMemberProfile
sqoop export --connect "jdbc:sqlserver://172.31.12.4;username=TestUsr;password=Welcome#1;database=OperationPig" --table B_001_InsuredMemberProfile --export-dir /user/sfox/output/WHA/B_001_InsuredMemberProfile/* --columns issueridentifier,subscriberindicator,subscriberidentifier,insuranceplanidentifier,coveragestartdate,coverageenddate,enrollmentmaintenancetypecode,insuranceplanpremiumamount,exchangerateareaidentifier,hsaproductkey,hsariskpoolkey,riskadjustedindicator,hsalegalentitykey,hsarateareakey,hsalifestagekey,hsametallevelkey,hsagrandfatheredplan,hsanewmember,hsaissuerstate,hsamemberstate,hsamembergeokey,hsacsr,hsamemberincome,hsaonexchange,memberreckey,insuredmemberidentifier,groupidentifier,groupname,subgroupidentifier,subgroupname,contractnumber,relationship,membername,ageatenrollment,memberpremiumamount,billablememberindicator,hsameaccepted,gcf --input-null-string '\\N' --input-null-non-string '\\N' -input-fields-terminated-by "|" -batch -m 4
#B_000_InsuredMember
sqoop export --connect "jdbc:sqlserver://172.31.12.4;username=TestUsr;password=Welcome#1;database=OperationPig" --table B_000_InsuredMember --export-dir /user/sfox/output/WHA/B_000_InsuredMember/* --columns recordidentifier,insuredmemberidentifier,insuredmemberbirthdate,insuredmembergendercode --input-null-string '\\N' --input-null-non-string '\\N' -input-fields-terminated-by "|" -batch -m 4
#B_004_PlanInfo
sqoop export --connect "jdbc:sqlserver://172.31.12.4;username=TestUsr;password=Welcome#1;database=OperationPig" --table B_004_PlanInfo --export-dir /user/sfox/output/WHA/B_004_PlanInfo/* --columns client,issuer,planriskadjustmentmodel,issuerstate,riskpool,producttype,channel,metallevel,networktype,plankey,insuranceplan,legalentitykey,issuerkey,statekey,planriskadjustmentmodelkey,riskpoolkey,productkey,channelkey,metallevelkey,networkkey,riskadjustedindicator,grandfatheredplanindicator,dateoflastupdate --input-null-string '\\N' --input-null-non-string '\\N' -input-fields-terminated-by "|" -batch -m 4 
#B_003_PharmacyClaimDetail
sqoop export --connect "jdbc:sqlserver://172.31.12.4;username=TestUsr;password=Welcome#1;database=OperationPig" --table B_003_PharmacyClaimDetail --export-dir /user/sfox/output/WHA/B_003_PharmacyClaimDetail/* --columns insuranceplanidentifier,insuredmemberidentifier,claimidentifier,claimprocesseddatetime,prescriptionfilldate,insurerclaimpaiddate,prescriptionservicereferencenumber,nationaldrugcode,dispensingprovideridqualifier,dispensingprovideridentifier,prescriptionfillnumber,dispensingstatuscode,voidreplacecode,allowedtotalcostamount,policypaidamount,derivedserviceclaimindicator,memberreckey --input-null-string '\\N' --input-null-non-string '\\N' -input-fields-terminated-by "|" -batch -m 4
#B_003a_PharmacyClaimAmount
sqoop export --connect "jdbc:sqlserver://172.31.12.4;username=TestUsr;password=Welcome#1;database=OperationPig" --table B_003a_PharmacyClaimAmount --export-dir /user/sfox/output/WHA/B_003a_PharmacyClaimAmount/* --columns insuredmemberidentifier,claimidentifier,allowedtotalamount,policypaidtotalamount,servicefromdate,servicetodate,memberreckey,claimyear,claimmonth --input-null-string '\\N' --input-null-non-string '\\N' -input-fields-terminated-by "|" -batch -m 4
